layout_spectrum: 0.9246294
color:
  saturation: 0.2872094
  lightness: 0.6419278
  brandStrength: 0.5756792
  brandColors:
    - '#C6C4BE'
    - '#16171F'
    - '#02419A'
    - '#A3292F'
    - '#F3CE16'
  rhythmicContrast: 0.9544944
typography_spectrum: 0.1353285
name: Philippa Parker-Barnes Visual Artist
